version: "3.2"
services:

   app:
        container_name: app
        image: douglasdecco/app   
        restart: always
        build: 
            context: ./node
            dockerfile: Dockerfile             
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s docker-entrypoint.sh     
        command: "app.js"
        tty: true
        networks: 
            - minharede
        ports: 
            - "3000:3000"
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "localhost:3000"]
        #     interval: 3s
        #     timeout: 10s
        #     retries: 30
        #     start_period: 15s
        depends_on: 
            - db

   nginx:
        container_name: nginx
        image: douglasdecco/nginx
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile      
        ports:
            - 8080:80
        networks: 
            - minharede
        depends_on:
            - app

   db:
        container_name: db
        image: mysql:5.7
        command: --innodb-use-native-aio=0        
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        # ports:
        #     - 3306
        networks: 
            - minharede   

networks: 
  minharede:
    driver: bridge    