version: "3.2"
services:
   
   app:
        build: app
        container_name: app
        restart: always
        tty: true
        build: .
        networks: 
            - minharede
        environment: 
             - PORT=3000
        ports: 
            - "3000:3000"
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "localhost:3000"]
        #     interval: 3s
        #     timeout: 10s
        #     retries: 30
        #     start_period: 15s
        depends_on: 
            - db

   db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - minharede

   nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile-nginx
        ports:
            - 8080:8080
        volumes:
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - minharede        
        depends_on: 
            - app
            #app:
            #    condition: service_healthy    

networks: 
  minharede:
    driver: bridge    