version: "3.2"
services:
   nginx:
       container_name: nginx
       image: nginx:1.17.8
       ports:
           - 8080:8080
       volumes:
           - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
       networks: 
           - minharede
   app:
        build: app
        container_name: app
        restart: always
        build: .
        networks: 
            - minharede
        environment: 
             - PORT=3000
        ports: 
            - "3000:3000"
        depends_on: 
            - db


   db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - minharede

networks: 
  minharede:
    driver: bridge    